version: '3.7'
services:
  microservicio1-cesarm: #microservicio1
    container_name: microservicio1-cesarm
    image: cesarmoralesh/asesorias-micro2:v1
    ports:
      - "4000"
    networks:
      - asesorias-red 
    environment:
      CONTAINET_HOST: microservicio1  
 ###
  microservicio2-cesarm: #microservicio2
    container_name: microservicio2-cesarm
    image: cesarmoralesh/asesorias-micro2:v1
    ports:
      - "4000"
    networks:
      - asesorias-red
    environment:
      CONTAINET_HOST: microservicio2  
  ###
  microservicio3-cesarm: #microservicio3
    container_name: microservicio3-cesarm
    image: cesarmoralesh/asesorias-micro2:v1
    ports:
      - "4000"
    networks:
      - asesorias-red
    environment:
      CONTAINET_HOST: microservicio3
  load-balancer-cesarm: #load balancer
    container_name: load-balancer-cesarm
    image: load-balancer-cesarm:v1
    build: 
      context: ./load-balancer
    ports:
      - "6076:80"
    networks:
      - asesorias-red 
    depends_on:
      - microservicio1-cesarm
      - microservicio2-cesarm
      - microservicio3-cesarm
    restart: always 

networks: 
  asesorias-red:

