version: '3.7'
services:
  microservicio1-cesar: #microservicio1
    container_name: microservicio1-cesar
    image: cesarmoralesh/asesorias-micro2:v1
    ports:
      - "4000"
    networks:
      - asesorias-red 
    environment:
      CONTAINET_HOST: microservicio1  
 ###
  microservicio2-cesar: #microservicio2
    container_name: microservicio2-cesar
    image: cesarmoralesh/asesorias-micro2:v1
    ports:
      - "4000"
    networks:
      - asesorias-red
    environment:
      CONTAINET_HOST: microservicio2  
  ###
  microservicio3-cesar: #microservicio3
    container_name: microservicio3-cesar
    image: cesarmoralesh/asesorias-micro2:v1
    ports:
      - "4000"
    networks:
      - asesorias-red
    environment:
      CONTAINET_HOST: microservicio3
  load-balancer-cesar: #load balancer
    container_name: load-balancer-cesar
    image: load-balancer-cesar:v1
    build: 
      context: ./load-balancer
    ports:
      - "8080:80"
    networks:
      - asesorias-red 
    depends_on:
      - microservicio1-cesar
      - microservicio2-cesar
      - microservicio3-cesar
    restart: always 

networks: 
  asesorias-red:

